export const SET_CURRENT_LOCATION_KEY = 'SET_CURRENT_LOCATION_KEY';
export const SET_FIVE_DAYS_FORECAST = 'SET_FIVE_DAYS_FORECAST';
export const SET_WEATHER = 'SET_WEATHER';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING = 'SET_LOADING';